version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: money-over-time-mongodb
    command: --replSet rs0
    volumes:
      - ./tmp/db/:/data/db/
    ports:
      - '27017:27017'
  mongosetup:
    image: mongo:latest
    depends_on:
      - mongodb
    restart: 'no'
    entrypoint:
      [
        'bash',
        '-c',
        "sleep 10 && mongo --host mongodb:27017 --eval 'rs.initiate()' && exit 0"
      ]

networks:
  default:
    name: money-over-time-network
